In [1]:
import torch
import numpy as np

### 2.3.1. 标量
标量由只有一个元素的张量表示

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
z = torch.tensor([3.0])
x, y, z, x is z

(tensor(3.), tensor(2.), tensor([3.]), False)

### 2.3.2. 向量

In [3]:
x = torch.arange(4)
x,x[3],len(x)

(tensor([0, 1, 2, 3]), tensor(3), 4)

请注意，维度（dimension）这个词在不同上下文时往往会有不同的含义，这经常会使人感到困惑。
为了清楚起见，我们在此明确一下：
向量或轴的维度被用来表示向量或轴的长度，**即向量或轴的元素数量**。
然而，张量的维度用来表示张量具有的轴数。
在这个意义上，张量的某个轴的维数就是这个轴的长度。

### 2.3.3. 矩阵
![矩阵的约定表示](imgs/2_1_2运算符1.png)

In [4]:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### 2.3.4. 张量
就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。 张量（本小节中的“张量”指代数对象）为我们提供了描述具有任意数量轴的 n 维数组的通用方法。 例如，向量是一阶张量，矩阵是二阶张量。 张量用特殊字体的大写字母表示（例如， X 、 Y 和 Z ），

In [5]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5. 张量算法的基本性质
标量、向量、矩阵和任意数量轴的张量（本小节中的“张量”指代数对象）有一些实用的属性。 例如，你可能已经从按元素操作的定义中注意到，任何按元素的一元运算都不会改变其操作数的形状。 同样，给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量。 例如，将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法。

In [6]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

具体而言，两个矩阵的按元素乘法称为Hadamard积（Hadamard product）（数学符号 ⊙ ）。
将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘

In [7]:
A * B, A + 2

(tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]),
 tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]))

### 2.3.6. 降维

In [8]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。

In [9]:
A,A.shape,A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

我们还可以指定张量沿哪一个轴来通过求和降低维度。
以矩阵为例，为了通过求和所有行的元素来降维（轴0），我们可以在调用函数时指定axis=0。
由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。

In [10]:
A.sum(axis=0), A.sum(axis=0).shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [11]:
# 指定axis=1将通过汇总所有列的元素降维（轴1）。因此，输入轴1的维数在输出形状中消失。
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [12]:
# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。
A.sum(axis=[0, 1])  # Same as A.sum()

tensor(190.)

### 补充张量sum

In [13]:
a = torch.arange(24).reshape(2,3,4)
a, a.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 torch.Size([2, 3, 4]))

In [14]:
a.sum()

tensor(276)

In [15]:
# 沿着axis=0的维度降维，A.sum的shape少了第一个2
a.sum(axis=0),a.sum(axis=0).shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [16]:
a.sum(axis=1)

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [17]:
a.sum(axis=2)

tensor([[ 6, 22, 38],
        [54, 70, 86]])

note:
可以看出，当指定axis=2时，就是对最内层的数据求和。
axis=1时，对中间括号的所有元素。。。。

一个与求和相关的量是平均值（mean或average）。
我们通过将总和除以元素总数来计算平均值。 在代码中，我们可以调用函数来计算任意形状张量的平均值。

In [18]:
A.mean(), A.sum() / A.numel(), A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor(9.5000),
 tensor(9.5000),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]))

##### 2.3.6.1. 非降维求和
但是，有时在调用函数来计算总和或均值时保持轴数不变会很有用。
例如，由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A。

In [19]:
A, A.sum(axis=1),A.sum(axis=1,keepdims=True)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]))

In [20]:
sum_A = A.sum(axis=1, keepdims=True)
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

如果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），
我们可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。

In [21]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [22]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [23]:
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

### 2.3.7. 点积（Dot Product）
我们已经学习了按元素操作、求和及平均值。 另一个最基本的操作之一是点积。
给定两个向量 x,y∈Rd ， 它们的点积（dot product） 是相同位置的按元素乘积的和

点积的作用
![点积的作用](imgs/2_3_7点积1.png)

In [24]:
y = torch.ones(4,dtype=torch.float32)
x, y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [25]:
# 注意，我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x * y),x*y, x*y.T

(tensor(6.), tensor([0., 1., 2., 3.]), tensor([0., 1., 2., 3.]))

### 2.3.8. 矩阵-向量积
![矩阵-向量积](imgs/2_3_8矩阵-向量积1.png)

In [26]:
A,x,A.shape,x.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]))

In [27]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

### 2.3.9. 矩阵-矩阵乘法
> 矩阵-矩阵乘法可以简单地称为矩阵乘法，不应与“Hadamard积”混淆。（Hadamard product）（数学符号 ⊙ ）

In [28]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

#### 2.3.10. 范数
线性代数中最有用的一些运算符是范数（norm）。
非正式地说，一个向量的范数告诉我们一个向量有多大。
这里考虑的大小（size）概念不涉及维度，而是分量的大小。

其中，在 L2 范数中常常省略下标 2 ，也就是说 ∥x∥ 等同于 ∥x∥_2 。 在代码中，我们可以按如下方式计算向量的 L2 范数。

In [29]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

在深度学习中，我们更经常地使用 L2 范数的平方。 你还会经常遇到 L1 范数，它表示为向量元素的绝对值之和

In [30]:
torch.abs(u).sum()

tensor(7.)

Frobenius范数满足向量范数的所有性质，它就像是矩阵形向量的 L2 范数
![Frobenius范数](imgs/2_3_10范数1.png)

#### 2.3.10.1. 范数和目标
在深度学习中，我们经常试图解决优化问题：
+ 最大化分配给观测数据的概率;
+ 最小化预测和真实观测之间的距离。

用向量表示物品（如单词、产品或新闻文章），以便最小化相似项目之间的距离，最大化不同项目之间的距离。
目标，或许是深度学习算法最重要的组成部分（除了数据），通常被表达为范数。